In [3]:
#https://school.programmers.co.kr/learn/courses/30/lessons/176963
#사진들을 보며 추억에 젖어 있던 루는 사진별로 추억 점수를 매길려고 합니다.
#사진 속에 나오는 인물의 그리움 점수를 모두 합산한 값이 해당 사진의 추억 점수가 됩니다.
#예를 들어 사진 속 인물의 이름이 ["may", "kein", "kain"]이고 각 인물의 그리움 점수가 [5점, 10점, 1점]일 때 해당 사진의 추억 점수는 16(5 + 10 + 1)점이 됩니다.
#다른 사진 속 인물의 이름이 ["kali", "mari", "don", "tony"]이고 ["kali", "mari", "don"]의 그리움 점수가 각각 [11점, 1점, 55점]]이고, "tony"는 그리움 점수가 없을 때, 
#이 사진의 추억 점수는 3명의 그리움 점수를 합한 67(11 + 1 + 55)점입니다.

#그리워하는 사람의 이름을 담은 문자열 배열 name, 각 사람별 그리움 점수를 담은 정수 배열 yearning, 
#각 사진에 찍힌 인물의 이름을 담은 이차원 문자열 배열 photo가 매개변수로 주어질 때, 
#사진들의 추억 점수를 photo에 주어진 순서대로 배열에 담아 return하는 solution 함수를 완성해주세요.

def solution1(name, yearning, photo):
    answer = []
    people_dic = {}
    for i, person in enumerate(name):
        people_dic[person] = yearning[i]
    for people in photo:
        total = 0
        for person in people:
            if person in people_dic:
                total += people_dic[person]
        answer.append(total)

    return answer

print(solution1(["may", "kein", "kain", "radi"], [5, 10, 1, 3], [["may", "kein", "kain", "radi"], ["may", "kein", "brin", "deny"], ["kon", "kain", "may", "coni"]])) #answer = [19, 15, 6]
print(solution1(["kali", "mari", "don"], [11, 1, 55], [["kali", "mari", "don"], ["pony", "tom", "teddy"], ["con", "mona", "don"]])) #answer = [67, 0, 55]
print(solution1(["may", "kein", "kain", "radi"], [5, 10, 1, 3], [["may"], ["kein", "deny", "may"], ["kon", "coni"]])) #answer = [5, 15, 0]

[19, 15, 6]
[67, 0, 55]
[5, 15, 0]

In [4]:
#https://school.programmers.co.kr/learn/courses/30/lessons/140108
#문자열 s가 입력되었을 때 다음 규칙을 따라서 이 문자열을 여러 문자열로 분해하려고 합니다.

#먼저 첫 글자를 읽습니다. 이 글자를 x라고 합시다.
#이제 이 문자열을 왼쪽에서 오른쪽으로 읽어나가면서, x와 x가 아닌 다른 글자들이 나온 횟수를 각각 셉니다.
#처음으로 두 횟수가 같아지는 순간 멈추고, 지금까지 읽은 문자열을 분리합니다.
#s에서 분리한 문자열을 빼고 남은 부분에 대해서 이 과정을 반복합니다. 남은 부분이 없다면 종료합니다.
#만약 두 횟수가 다른 상태에서 더 이상 읽을 글자가 없다면, 역시 지금까지 읽은 문자열을 분리하고, 종료합니다.

#문자열 s가 매개변수로 주어질 때, 위 과정과 같이 문자열들로 분해하고, 분해한 문자열의 개수를 return 하는 함수 solution을 완성하세요.

def word_splite(s):
    first_word = s[0]
    same = 0
    different = 0
    
    for i, word in enumerate(s):
        if first_word == word:
            same += 1
        else:
            different += 1
        if same == different:
            break
    if len(s) == i:
        front_s = s
        back_s = ''
    else:
        front_s = s[:i+1]
        back_s = s[i+1:]      
    return front_s, back_s
    

def solution2(s):
    splited_word = []
    front, back  = word_splite(s)
    while back !='':
        splited_word.append(front)
        front, back = word_splite(back)
    splited_word.append(front)
    answer = len(splited_word)
    return answer
  
print(solution2("banana")) #answer = 3
print(solution2("abracadabra")) #answer = 6
print(solution2("aaabbaccccabba")) #answer = 3

3
6
3